(defvar *crowleycards* nil)
(setf   *crowleycards* '((1  . (1  "wands"  "fire"))
			 (2  . (1  "cups"   "water"))
			 (3  . (1  "swords" "air"))
			 (4  . (1  "coins"  "earth"))
			 (5  . (12 "wands"  "knight"))
			 (6  . (13 "wands"  "queen"))
			 (7  . (14 "wands"  "king"))
			 (8  . (11 "wands"  "page"))
			 (9  . (12 "cups"   "knight"))
			 (10 . (13 "cups"   "queen"))
			 (11 . (14 "cups"   "king"))
			 (12 . (11 "cups"   "page"))
			 (13 . (12 "swords" "knight"))
			 (14 . (13 "swords" "queen"))
			 (15 . (14 "swords" "king"))
			 (16 . (11 "swords" "page"))
			 (17 . (12 "coins"  "knight"))
			 (18 . (13 "coins"  "queen"))
			 (19 . (14 "coins"  "king"))
			 (20 . (11 "coins"  "page"))
			 (21 . (5  "wands"  "strife"))
			 (22 . (6  "wands"  "victory"))
			 (23 . (7  "wands"  "valour"))
			 (24 . (8  "coins"  "prudence"))
			 (25 . (9  "coins"  "material gain"))
			 (26 . (10 "coins"  "wealth"))
			 (27 . (2  "swords" "peace restored"))
			 (28 . (3  "swords" "sorrow"))
			 (29 . (4  "swords" "rest from strife"))
			 (30 . (5  "cups"   "loss in pleasure"))
			 (31 . (6  "cups"   "pleasure"))
			 (32 . (7  "cups"   "illusory success"))
			 (33 . (8  "wands"  "swiftness"))
			 (34 . (9  "wands"  "great strength"))
			 (35 . (10 "wands"  "oppression"))
			 (36 . (2  "coins"  "harmonious change"))
			 (37 . (3  "coins"  "material works"))
			 (38 . (4  "coins"  "earthly power"))
			 (39 . (5  "swords" "defeat"))
			 (40 . (6  "swords" "earned success"))
			 (41 . (7  "swords" "unstable effort"))
			 (42 . (8  "cups"   "abandoned success"))
			 (43 . (9  "cups"   "material happiness"))
			 (44 . (10 "cups"   "perfected success"))
			 (45 . (2  "wands"  "dominion"))
			 (46 . (3  "wands"  "established strength"))
			 (47 . (4  "wands"  "perfected strength"))
			 (48 . (5  "coins"  "material trouble"))
			 (49 . (6  "coins"  "material success"))
			 (50 . (7  "coins"  "success unfulfilled"))
			 (51 . (8  "swords" "shortened force"))
			 (52 . (9  "swords" "despair and cruelty"))
			 (53 . (10 "swords" "ruin"))
			 (54 . (2  "cups"   "love"))
			 (55 . (3  "cups"   "abundance"))
			 (56 . (4  "cups"   "blended pleasure"))
			 (57 . (0  "major"  "the fool"))
			 (58 . (1  "major"  "the magician"))
			 (59 . (2  "major"  "the high priestess"))
			 (60 . (3  "major"  "the empress"))
			 (61 . (4  "major"  "the emperor"))
			 (62 . (5  "major"  "the heirophant"))
			 (63 . (6  "major"  "the lovers"))
			 (64 . (7  "major"  "the chariot"))
			 (65 . (11 "major"  "strength"))
			 (66 . (9  "major"  "the hermit"))
			 (67 . (10 "major"  "the wheel"))
			 (68 . (8  "major"  "justice"))
			 (69 . (12 "major"  "the hanged man"))
			 (70 . (13 "major"  "death"))
			 (71 . (14 "major"  "temperance"))
			 (72 . (15 "major"  "the devil"))
			 (73 . (16 "major"  "the tower"))
			 (74 . (17 "major"  "the star"))
			 (75 . (18 "major"  "the moon"))
			 (76 . (19 "major"  "the sun"))
			 (77 . (20 "major"  "judgement"))
			 (78 . (21 "major"  "the world"))))
