(defvar *crowleycards* nil)
;; here i use the basic definitions of the cards as outlined in crowley's work
;; regarding the book of thoth. the associated images - at least for now - are
;; actually the rider-waite book/deck as designed by arthur edward waite & as
;; painted by pamela coleman smith. an easy way to add image libraries, i.e.
;; support for multple "decks" is on the project's todo list.
(setf   *crowleycards* '((1  . (1  "wands"  "fire" #P"images/wands1.jpg"))
			 (2  . (1  "cups"   "water" #P"images/cups1.jpg"))
			 (3  . (1  "swords" "air" #P"images/swords1.jpg"))
			 (4  . (1  "coins"  "earth" #P"images/coins1.jpg"))
			 (5  . (12 "wands"  "knight" #P"images/wands12.jpg"))
			 (6  . (13 "wands"  "queen" #P"images/wands13.jpg"))
			 (7  . (14 "wands"  "king" #P"images/wands14.jpg"))
			 (8  . (11 "wands"  "page" #P"images/wands11.jpg"))
			 (9  . (12 "cups"   "knight" #P"images/cups12.jpg"))
			 (10 . (13 "cups"   "queen" #P"images/cups13.jpg"))
			 (11 . (14 "cups"   "king" #P"images/cups14.jpg"))
			 (12 . (11 "cups"   "page" #P"images/cups11.jpg"))
			 (13 . (12 "swords" "knight" #P"images/swords12.jpg"))
			 (14 . (13 "swords" "queen" #P"images/swords13.jpg"))
			 (15 . (14 "swords" "king" #P"images/swords14.jpg"))
			 (16 . (11 "swords" "page" #P"images/wands03.png"))
			 (17 . (12 "coins"  "knight" #P"images/wands03.png"))
			 (18 . (13 "coins"  "queen" #P"images/wands03.png"))
			 (19 . (14 "coins"  "king" #P"images/wands03.png"))
			 (20 . (11 "coins"  "page" #P"images/wands03.png"))
			 (21 . (5  "wands"  "strife" #P"images/wands03.png"))
			 (22 . (6  "wands"  "victory" #P"images/wands03.png"))
			 (23 . (7  "wands"  "valour" #P"images/wands7.png"))
			 (24 . (8  "coins"  "prudence" #P"images/coins8.png"))
			 (25 . (9  "coins"  "material gain" #P"images/coins9.png"))
			 (26 . (10 "coins"  "wealth" #P"images/coins10.png"))
			 (27 . (2  "swords" "peace restored" #P"images/swords2.png"))
			 (28 . (3  "swords" "sorrow" #P"images/swords3.png"))
			 (29 . (4  "swords" "rest from strife" #P"images/swords4.png"))
			 (30 . (5  "cups"   "loss in pleasure" #P"images/cups5.png"))
			 (31 . (6  "cups"   "pleasure" #P"images/cups6.png")
			 (32 . (7  "cups"   "illusory success" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (33 . (8  "wands"  "swiftness" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (34 . (9  "wands"  "great strength" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (35 . (10 "wands"  "oppression" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (36 . (2  "coins"  "harmonious change" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (37 . (3  "coins"  "material works" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (38 . (4  "coins"  "earthly power" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (39 . (5  "swords" "defeat" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (40 . (6  "swords" "earned success" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (41 . (7  "swords" "unstable effort" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (42 . (8  "cups"   "abandoned success" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (43 . (9  "cups"   "material happiness" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (44 . (10 "cups"   "perfected success" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (45 . (2  "wands"  "dominion" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (46 . (3  "wands"  "established strength" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (47 . (4  "wands"  "perfected strength" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (48 . (5  "coins"  "material trouble" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (49 . (6  "coins"  "material success" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (50 . (7  "coins"  "success unfulfilled" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (51 . (8  "swords" "shortened force" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (52 . (9  "swords" "despair and cruelty" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (53 . (10 "swords" "ruin" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (54 . (2  "cups"   "love" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (55 . (3  "cups"   "abundance" #P"/home/jo/2014/cl-tarot/images/wands03.png"))
			 (56 . (4  "cups"   "blended pleasure" #P"/home/jo/2014/cl-tarotimages/wands03.png"))
			 (57 . (0  "maj"  "the fool"))
			 (58 . (1  "maj"  "the magician"))
			 (59 . (2  "maj"  "the high priestess"))
			 (60 . (3  "maj"  "the empress"))
			 (61 . (4  "maj"  "the emperor"))
			 (62 . (5  "maj"  "the heirophant"))
			 (63 . (6  "maj"  "the lovers"))
			 (64 . (7  "maj"  "the chariot"))
			 (65 . (11 "maj"  "strength"))
			 (66 . (9  "maj"  "the hermit"))
			 (67 . (10 "maj"  "the wheel"))
			 (68 . (8  "maj"  "justice"))
			 (69 . (12 "maj"  "the hanged man"))
			 (70 . (13 "maj"  "death"))
			 (71 . (14 "maj"  "temperance"))
			 (72 . (15 "maj"  "the devil"))
			 (73 . (16 "maj"  "the tower"))
			 (74 . (17 "maj"  "the star"))
			 (75 . (18 "maj"  "the moon"))
			 (76 . (19 "maj"  "the sun"))
			 (77 . (20 "maj"  "judgement"))
			 (78 . (21 "maj"  "the world"))))
