(defvar *crowleycards* nil)
;; here i use the basic definitions of the cards as outlined in crowley's work
;; regarding the book of thoth. the associated images - at least for now - are
;; actually the rider-waite book/deck as designed by arthur edward waite & as
;; painted by pamela coleman smith. an easy way to add image libraries, i.e.
;; support for multple "decks" is on the project's todo list.
(setf   *crowleycards* '((1  . (1  "wands"  "fire" #P"images/wands1.png"))
			 (2  . (1  "cups"   "water" #P"images/cups1.png"))
			 (3  . (1  "swords" "air" #P"images/swords1.png"))
			 (4  . (1  "coins"  "earth" #P"images/coins1.png"))
			 (5  . (12 "wands"  "knight" #P"images/wands12.png"))
			 (6  . (13 "wands"  "queen" #P"images/wands13.png"))
			 (7  . (14 "wands"  "king" #P"images/wands14.png"))
			 (8  . (11 "wands"  "page" #P"images/wands11.png"))
			 (9  . (12 "cups"   "knight" #P"images/cups12.png"))
			 (10 . (13 "cups"   "queen" #P"images/cups13.png"))
			 (11 . (14 "cups"   "king" #P"images/cups14.png"))
			 (12 . (11 "cups"   "page" #P"images/cups11.png"))
			 (13 . (12 "swords" "knight" #P"images/swords12.png"))
			 (14 . (13 "swords" "queen" #P"images/swords13.png"))
			 (15 . (14 "swords" "king" #P"images/swords14.png"))
			 (16 . (11 "swords" "page" #P"images/swords11.png"))
			 (17 . (12 "coins"  "knight" #P"images/coins12.png"))
			 (18 . (13 "coins"  "queen" #P"images/coins13.png"))
			 (19 . (14 "coins"  "king" #P"images/coins14.png"))
			 (20 . (11 "coins"  "page" #P"images/coins11.png"))
			 (21 . (5  "wands"  "strife" #P"images/wands5.png"))
			 (22 . (6  "wands"  "victory" #P"images/wands6.png"))
			 (23 . (7  "wands"  "valour" #P"images/wands7.png"))
			 (24 . (8  "coins"  "prudence" #P"images/coins8.png"))
			 (25 . (9  "coins"  "material gain" #P"images/coins9.png"))
			 (26 . (10 "coins"  "wealth" #P"images/coins10.png"))
			 (27 . (2  "swords" "peace restored" #P"images/swords2.png"))
			 (28 . (3  "swords" "sorrow" #P"images/swords3.png"))
			 (29 . (4  "swords" "rest from strife" #P"images/swords4.png"))
			 (30 . (5  "cups"   "loss in pleasure" #P"images/cups5.png"))
			 (31 . (6  "cups"   "pleasure" #P"images/cups6.png"))
			 (32 . (7  "cups"   "illusory success" #P"images/cups7.png"))
			 (33 . (8  "wands"  "swiftness" #P"images/wands8.png"))
			 (34 . (9  "wands"  "great strength" #P"images/wands9.png"))
			 (35 . (10 "wands"  "oppression" #P"images/wands10.png"))
			 (36 . (2  "coins"  "harmonious change" #P"images/coins2.png"))
			 (37 . (3  "coins"  "material works" #P"images/coins3.png"))
			 (38 . (4  "coins"  "earthly power" #P"images/coins4.png"))
			 (39 . (5  "swords" "defeat" #P"images/swords5.png"))
			 (40 . (6  "swords" "earned success" #P"images/swords6.png"))
			 (41 . (7  "swords" "unstable effort" #P"images/swords7.png"))
			 (42 . (8  "cups"   "abandoned success" #P"images/cups8.png"))
			 (43 . (9  "cups"   "material happiness" #P"images/cups9.png"))
			 (44 . (10 "cups"   "perfected success" #P"images/cups10.png"))
			 (45 . (2  "wands"  "dominion" #P"images/wands2.png"))
			 (46 . (3  "wands"  "established strength" #P"images/wands3.png"))
			 (47 . (4  "wands"  "perfected strength" #P"images/wands4.png"))
			 (48 . (5  "coins"  "material trouble" #P"images/coins5.png"))
			 (49 . (6  "coins"  "material success" #P"images/coins6.png"))
			 (50 . (7  "coins"  "success unfulfilled" #P"images/coins7.png"))
			 (51 . (8  "swords" "shortened force" #P"images/swords8.png"))
			 (52 . (9  "swords" "despair and cruelty" #P"images/swords9.png"))
			 (53 . (10 "swords" "ruin" #P"images/swords10.png"))
			 (54 . (2  "cups"   "love" #P"images/cups2.png"))
			 (55 . (3  "cups"   "abundance" #P"images/cups3.png"))
			 (56 . (4  "cups"   "blended pleasure" #P"images/cups4.png"))
			 (57 . (0  "maj"  "the fool" #P"images/maj0.png"))
			 (58 . (1  "maj"  "the magician" #P"images/maj1.png"))
			 (59 . (2  "maj"  "the high priestess" #P"images/maj2.png"))
			 (60 . (3  "maj"  "the empress" #P"images/maj3.png"))
			 (61 . (4  "maj"  "the emperor" #P"images/maj4.png"))
			 (62 . (5  "maj"  "the heirophant" #P"images/maj5.png"))
			 (63 . (6  "maj"  "the lovers" #P"images/maj6.png"))
			 (64 . (7  "maj"  "the chariot" #P"images/maj7.png"))
			 (65 . (11 "maj"  "strength" #P"images/maj11.png"))
			 (66 . (9  "maj"  "the hermit" #P"images/maj9.png"))
			 (67 . (10 "maj"  "the wheel" #P"images/maj10.png"))
			 (68 . (8  "maj"  "justice" #P"images/maj8.png"))
			 (69 . (12 "maj"  "the hanged man" #P"images/maj12.png"))
			 (70 . (13 "maj"  "death" #P"images/maj13.png"))
			 (71 . (14 "maj"  "temperance" #P"images/maj14.png"))
			 (72 . (15 "maj"  "the devil" #P"images/maj15.png"))
			 (73 . (16 "maj"  "the tower" #P"images/ma16.png"))
			 (74 . (17 "maj"  "the star" #P"images/maj17.png"))
			 (75 . (18 "maj"  "the moon" #P"images/maj18.png"))
			 (76 . (19 "maj"  "the sun" #P"images/maj19.png"))
			 (77 . (20 "maj"  "judgement" #P"images/maj20.png"))
			 (78 . (21 "maj"  "the world" #P"images/maj21.png"))))
